### ISSUE TITLE
interested to change the css into a sass structure?

### ISSUE THREAD

**Issue by eversthomas** [halfmoonui/halfmoon#15]
I would like to help if this is liked...

**Comment by halfmoonui** [comment]
To be honest, personally I want to focus **completely** on CSS variables, instead of SASS. But, you are more than welcome to create a PR with SASS structure implemented.

**Comment by halfmoonui** [comment]
@eversthomas This project has fully committed to CSS variables instead of SASS. If you would like, you can fork this and implement a SASS structure. I would be more than happy to link that repo in the README and also on the website. 

I will go ahead and close this issue. You can re-open it if you think the issue is still not resolved, or open another issue.
