### ISSUE TITLE
Cannot get Sidebar Toggle to work in React

### ISSUE THREAD

**Issue by brettdoyle44** [halfmoonui/halfmoon#31]
I have looked through the issue queue and thought that upgrading to version 1.0.4 would fix this issue but it hasn't. For some reason I am unable to call the Sidebar toggle, but the dark mode toggle works.

Here is the code:

```
import halfmoon from 'halfmoon';
```

```
useEffect(() => {
    if (isMounted.current) {
      halfmoon.onDOMContentLoaded();
      onLoad();
    }
    return () => (isMounted.current = true);
  }, []);
```

```
<div className="navbar-content">
            <button
              id="toggle-sidebar-btn"
              className="btn btn-action"
              type="button"
              onClick={halfmoon.toggleSidebar()}
            >
```

**Comment by halfmoonui** [comment]
That's weird. Do you have the sidebar inside the page wrapper?

**Comment by visoft** [comment]
@halfmoonui -

There is one more change that needs to be implemented. In `toggleSidebar` it uses `this.pageWrapper` which is `undefined` changing this to `halfmoon.pageWrapper` should fix the sidebar issue for good. `this` in the context of the method is the window, not halfmoon. Also in `initStickyAlert` it uses `this` as well, both instances should change to `halfmoon.`.

When I tested 1.0.4, I must have been testing my altered copy of halfmoon.js not the 1.0.4 version. I apologize for that!

**Comment by halfmoonui** [comment]
@visoft But the `pageWrapper` and `stickyAlerts` are re-initalized in the `onDOMContentLoaded()` function. Wouldn't that mean that `this.pageWrapper` would refer to `halfmoon.pageWrapper`?

**Comment by visoft** [comment]
@halfmoonui - yes, just change the `this.` references to `halfmoon.`

**Comment by visoft** [comment]
Take a look at Function Context here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Description. Seems like you just need to use strict mode based on this: “Since the following code is not in strict mode, and because the value of this is not set by the call, this will default to the global object, which is window in a browser.”

**Comment by visoft** [comment]
Actually I enabled strict mode locally, and then `this` is `undefined` inside `toggleSidebar`.

**Comment by halfmoonui** [comment]
This is definitely a weird issue. Maybe the JS module needs to re-structured for use with virtual DOMs because of these weird bugs.

**Comment by visoft** [comment]
@brettdoyle44 - Here's the fix for React:
` <button className="btn btn-action" type="button" onClick={() => halfmoon.toggleSidebar()}>`

Just use an anonymous function to call `halfmoon.toggleSidebar()`, then `this` is not `window`.

If this works for you, I can put in a README PR so it can help others.

**Comment by halfmoonui** [comment]
@visoft Thank you for coming up with the quick fix. May I ask though, is there a way to structure the functions in a way so that an anonymous function isn't required to call `halfmoon` functions in React?

And regarding the PR, sure sounds good to me. I will update the docs after your PR goes through.

**Comment by visoft** [comment]
This way works as well:

`<button className="btn btn-action" type="button" onClick={halfmoon.toggleSidebar.bind(halfmoon)}>`

**Comment by visoft** [comment]
More information here about binding in React: https://reactjs.org/docs/faq-functions.html#why-is-binding-necessary-at-all

**Comment by halfmoonui** [comment]
The pull request has been merged. Hopefully that should help people who are using React. Again, thanks to @visoft for this PR. 

@brettdoyle44 Please let us know if that has fixed your issue.

**Comment by brettdoyle44** [comment]
@halfmoonui @visoft I got it to work but it's a bit odd how. So I initialize halfmoon.onDOMContentLoaded() on App.js which I thought would mean it's initialized for the Sidebar component that is imported there. Unfortunately that is not the case and I had to also initialize halfmoon.onDOMContentLoaded() in the Sidebar component as well. Any idea why? Do I need to initialize it in every component that uses a halfmoon method?

**Comment by halfmoonui** [comment]
When are you initializing `halfmoon.onDOMContentLoaded()` on your `App.js`? Are you using the `componentDidMount()` method?

**Comment by visoft** [comment]
He’s using a React hook, `useEffect`. I’m doing similar in my `App.js` as well, however my code is simpler:

```
import halfmoon from 'halfmoon';

useEffect(() => {
  halfmoon.onDOMContentLoaded();
}, []);
```

At the moment, I also have the root sidebar `div` in `App.JS’ not a separate component. I suspect that’s why mine is working ok. My guess for initializing twice, is because his root `sidebar div` is in a separate component.

**Comment by halfmoonui** [comment]
Yep. If its a separate component, then the function needs to be called in that component as well. If it is not a separate component, then you can just call it once, like the above comment mentions.

**Comment by brettdoyle44** [comment]
@halfmoonui @visoft Thanks guys. I will remember that for the future. Seems like it's only the sidebar it effects (right now).
