### ISSUE TITLE
Interactive Side Navigation

### ISSUE THREAD

**Issue by saumyasinghal747** [halfmoonui/halfmoon#51]
Hello! This is an amazing library - I'm the author of [YMath.io](https://ymath.io) and looking to redo the site from Bootstrap 4 to Halfmoon. 
One thing I want to implement in my site is a sidebar navigation for courses. So first the user would see the left image, then the right image. Could this be implemented? I'd really like to use Halfmoon for YMath.
 <img height="500px" src="https://user-images.githubusercontent.com/65318685/94182555-08699080-fe56-11ea-8def-c73c93e96970.png"/> <img height="500px" src="https://user-images.githubusercontent.com/65318685/94183277-081dc500-fe57-11ea-8c27-d8b432f835bf.png"/> 

If you can suggest a better, alternative form of navigation, then I am definitely open to hearing that too!

**Comment by halfmoonui** [comment]
Thank you for the kind words. What you want to do (if I understand correctly) can be pulled off using a bit of JavaScript. Probably a state variable that decides which sidebar content to show, and this state variable can be toggled by clicking on the links. 

However, this issue is out of scope for the framework, and moreover, this seems like a personal support question, not an issue with the repository and its codebase. For that reason, I will close it. You should probably post this (along with some more code to show that you tried to at least solve the problem yourself) to Stack Overflow using this tag: https://stackoverflow.com/questions/tagged/halfmoon
