### ISSUE TITLE
More file upload input styles like bootstrap or include in documentation

### ISSUE THREAD

**Issue by larsjarred9** [halfmoonui/halfmoon#60]
I would like to have more file inputs such as:
![image](https://user-images.githubusercontent.com/31996561/95042805-46c74100-06db-11eb-8ff6-053c0cce4b5b.png)

or atleast have those options listed in the documentation since I have absolutly 0 idea on how to make something like this at the moment with halfmoon.

Keep up the good work with the framework. I realy like the boostrap-like classes and the dark mode :) (PS: Light mode could have some improvment as someonelese already stated)

**Comment by halfmoonui** [comment]
These file inputs are basically just input groups. For example: 

```html
<div class="input-group">
  <div class="input-group-prepend">
    <span class="input-group-text">Upload</span>
  </div>
  <input type="text" class="form-control" placeholder="Browse file" readonly="readonly">
  <div class="input-group-append">
    <button class="btn" type="button">Browse</button>
  </div>
</div>
```
However, when it comes to the JavaScript part, you would have to implement them yourself. It should be easy enough if you use the implementation in `halfmoon.js` as a reference, because all it is really doing is changing the name of the file when the input element is used.
