### ISSUE TITLE
Navbar popup menu doesn't close when going to new route in Vue

### ISSUE THREAD

**Issue by digbyk** [halfmoonui/halfmoon#74]
Hi - first up, I love this project. Really easy to incorporate into an existing site and very well documented 👍

One thing I noticed, however, was that in my Vue application, <router-link>s in the navbar dropdown don't trigger closing the dropdown, so I have had to add workaround code to simulate re-clicking the button, but it's definitely not very elegant...

```html
<div
  id="navDropdown"
  class="dropdown-menu dropdown-menu-right w-200"
  aria-labelledby="navbar-dropdown-toggle-btn-1"
  @click="closeMenu"
>
  ...
</div>
```

```javascript
closeMenu: function() {
  const menu = document.getElementById("navDropdown");
  menu.click();
  // menu.firstChild.classList.remove("active"); // This seemed to work too but wasn't sure it was doing everything it needed.
  // menu.classList.remove("show");
},
```

I wonder if just widening the event.target.matches at  https://github.com/halfmoonui/halfmoon/blob/master/js/halfmoon.js#L312 would be better. I'll see if I can get that to work before creating a PR.

**Comment by halfmoonui** [comment]
Thank you! The dropdown component should work right out of the box with Vue. I assume you are using the npm package, did you call the `halfmoon.onDOMContentLoaded()` method after your component is loaded? You can read more here: https://www.gethalfmoon.com/docs/download/#using-npm

**Comment by digbyk** [comment]
Thanks for replying. I've tried various combinations of CDN and require/import, putting the `halfmoon.onDOMContentLoaded()` in App.vue and the component but nothing seems to work.

I tried starting from square one and creating a clean HTML page with the CDN link that didn't work for anchor links, but then I noticed that even on your site, clicking on the Github stars button, which opens in a new tab, doesn't close the popup. Maybe this is intentional, but it does seem to point to be the same thing.

It's been a long week, so I might be missing the obvious.

**Comment by halfmoonui** [comment]
Sorry for the late response. I misunderstood what you meant previously. What you are seeing is basically the default expected behavior, i.e. it is intentional. I do realize some other libraries wire up the dropdown menus to close when a link is closed (like Bootstrap), but I feel that paradigm is a bit limited, especially if you want forms and other components inside the menu. The only issue is the one your rightly pointed out - going to a new tab is a bit awkward because the menu stays open. If you are adamant about closing it, I guess you could attach the `data-toggle="dropdown"` to the link, but I do admit that it's a bit hacky.

**Comment by digbyk** [comment]
Understood. Thanks for taking the time to reply.
