### ISSUE TITLE
Request - Better mobile Navbar

### ISSUE THREAD

**Issue by james090500** [halfmoonui/halfmoon#79]
Would really like their to be a bertter way at handling a better mobile menu. Similar to how bootstrap use burgers?

**Comment by halfmoonui** [comment]
I opted for not going the Bootstrap route because I generally found it to too restrictive. And more importantly, I think it is one of the reasons which makes all the sites built with Bootstrap look the same.

The way it is right now, I think a lot of versatile designs are possible with Halfmoon's navbars, though the documentation is missing more complicated examples (my fault).

**Comment by james090500** [comment]
Closing as repo seems dead
